import "./globals.css";

export const metadata = {
  title: "商品搬家",
  description: "商品搬家 Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="cn">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      {children}
    </html>
  );
}
